
puts "The students of my cohort at Makers Academy"
puts "----------------"
puts "James Carter"
puts "Bill Bailey"
puts "Jim Franco"
puts "Will Homers"
puts "Jessica Rabbit"
puts "Jane Fonda"
puts "Jeremiah Cane"